import { BillAnalysis, BillCharge, BillFinding } from "../types";
import { formatCurrency } from "./currency";

/**
 * Renders a BillAnalysis as a self-contained, letterhead-style HTML document
 * meant to be passed to expo-print's Print.printToFileAsync({ html }) to
 * produce a shareable PDF report. Keep this in sync with the in-app results
 * screen in App.tsx, which shows the same data with the same grouping.
 */
export function buildReportHtml(analysis: BillAnalysis): string {
  const generatedAt = new Date().toLocaleString("en-CA", {
    dateStyle: "long",
    timeStyle: "short"
  });

  const needsAttention = analysis.charges.filter((charge) => charge.status !== "expected");
  const expected = analysis.charges.filter((charge) => charge.status === "expected");
  const delta =
    analysis.previousTotal != null ? roundMoney(analysis.totalDue - analysis.previousTotal) : null;

  return `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <style>${REPORT_STYLES}</style>
  </head>
  <body>
    <div class="letterhead">
      <div>
        <div class="brand">BillClear</div>
        <div class="tagline">Canadian telecom bill analysis report</div>
      </div>
      <div class="meta">
        <div>Generated ${escapeHtml(generatedAt)}</div>
        <div>Source: ${escapeHtml(providerLabel(analysis.provider))}</div>
      </div>
    </div>

    <h1 class="reportTitle">${escapeHtml(analysis.carrier)} bill &mdash; ${escapeHtml(analysis.billingPeriod)}</h1>

    <div class="summaryGrid">
      <div class="summaryCard">
        <div class="summaryLabel">Total due</div>
        <div class="summaryValue">${escapeHtml(formatCurrency(analysis.totalDue))}</div>
      </div>
      <div class="summaryCard">
        <div class="summaryLabel">Due date</div>
        <div class="summaryValue summaryValueSmall">${escapeHtml(analysis.dueDate)}</div>
      </div>
      <div class="summaryCard">
        <div class="summaryLabel">Change vs. previous bill</div>
        <div class="summaryValue summaryValueSmall ${delta != null && delta > 0 ? "negative" : "positive"}">
          ${delta != null ? escapeHtml(formatDelta(delta)) : "No prior bill"}
        </div>
      </div>
      <div class="summaryCard">
        <div class="summaryLabel">Scan confidence</div>
        <div class="summaryValue summaryValueSmall">${escapeHtml(capitalize(analysis.confidence ?? "medium"))}</div>
      </div>
    </div>

    <p class="summaryText">${escapeHtml(analysis.plainEnglishSummary)}</p>

    ${needsAttention.length > 0 ? renderAttentionBanner(needsAttention.length) : ""}

    ${analysis.history && analysis.history.length > 1 ? renderHistorySection(analysis.history) : ""}

    <h2 class="sectionTitle">Findings</h2>
    <div class="findingsList">
      ${analysis.findings.map(renderFinding).join("")}
    </div>

    ${
      needsAttention.length > 0
        ? `<h2 class="sectionTitle">Charges that need your attention (${needsAttention.length})</h2>
           <table class="chargeTable">
             <thead><tr><th>Charge</th><th>Status</th><th class="amountCol">Amount</th></tr></thead>
             <tbody>${needsAttention.map(renderChargeRow).join("")}</tbody>
           </table>`
        : `<p class="summaryText">No charges were flagged as new, changed, or questionable on this bill.</p>`
    }

    ${
      expected.length > 0
        ? `<h2 class="sectionTitle">Expected charges (${expected.length})</h2>
           <table class="chargeTable chargeTableMuted">
             <thead><tr><th>Charge</th><th class="amountCol">Amount</th></tr></thead>
             <tbody>${expected.map(renderExpectedChargeRow).join("")}</tbody>
           </table>`
        : ""
    }

    <h2 class="sectionTitle">Your rights</h2>
    <p class="rightsText">${escapeHtml(analysis.rightsNote)}</p>

    <div class="footer">
      Generated by BillClear from the bill file you provided. Verify totals against your original bill before
      sending a dispute. BillClear is not affiliated with ${escapeHtml(analysis.carrier)} or the CRTC.
    </div>
  </body>
</html>`;
}

function renderAttentionBanner(count: number): string {
  return `<div class="attentionBanner">${count} charge${count === 1 ? "" : "s"} on this bill ${
    count === 1 ? "looks" : "look"
  } new, changed, or worth questioning &mdash; see "Charges that need your attention" below.</div>`;
}

function renderHistorySection(history: { billingPeriod: string; totalDue: number }[]): string {
  const rows = history
    .map((point, index) => {
      const previous = index > 0 ? history[index - 1] : null;
      const delta = previous ? roundMoney(point.totalDue - previous.totalDue) : null;
      const isCurrent = index === history.length - 1;
      return `<tr class="${isCurrent ? "historyRowCurrent" : ""}">
        <td>${escapeHtml(point.billingPeriod)}${isCurrent ? ' <span class="currentTag">Current</span>' : ""}</td>
        <td class="amountCol">${escapeHtml(formatCurrency(point.totalDue))}</td>
        <td class="amountCol">${delta != null && delta !== 0 ? escapeHtml(formatDelta(delta)) : "&mdash;"}</td>
      </tr>`;
    })
    .join("");

  return `<h2 class="sectionTitle">Total due over time</h2>
    <table class="chargeTable">
      <thead><tr><th>Billing period</th><th class="amountCol">Total due</th><th class="amountCol">Change</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>`;
}

function renderFinding(finding: BillFinding): string {
  return `<div class="finding finding-${finding.severity}">
    <div class="findingTitle">${escapeHtml(finding.title)}</div>
    <div class="findingText">${escapeHtml(finding.description)}</div>
  </div>`;
}

function renderChargeRow(charge: BillCharge): string {
  return `<tr>
    <td>
      <div class="chargeName">${escapeHtml(charge.name)}</div>
      <div class="chargeExplanation">${escapeHtml(charge.explanation)}</div>
      ${charge.action ? `<div class="chargeAction">Suggested action: ${escapeHtml(charge.action)}</div>` : ""}
    </td>
    <td><span class="statusTag status-${charge.status}">${escapeHtml(capitalize(charge.status))}</span></td>
    <td class="amountCol">${escapeHtml(formatCurrency(charge.amount))}</td>
  </tr>`;
}

function renderExpectedChargeRow(charge: BillCharge): string {
  return `<tr>
    <td>${escapeHtml(charge.name)}</td>
    <td class="amountCol">${escapeHtml(formatCurrency(charge.amount))}</td>
  </tr>`;
}

function providerLabel(provider: BillAnalysis["provider"]): string {
  switch (provider) {
    case "local_parser":
      return "Private parser";
    case "claude":
      return "Cloud AI";
    case "mock":
      return "Test mock";
    case "openai":
      return "OpenAI";
    case "gemini":
      return "Gemini";
    default:
      return "Analysis engine";
  }
}

function roundMoney(value: number): number {
  return Number(value.toFixed(2));
}

function formatDelta(value: number): string {
  return `${value > 0 ? "+" : ""}${formatCurrency(value)}`;
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}

function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

const REPORT_STYLES = `
  * { box-sizing: border-box; }
  body {
    font-family: -apple-system, "Helvetica Neue", Arial, sans-serif;
    color: #2f423d;
    margin: 32px 36px;
    font-size: 13px;
    line-height: 1.5;
  }
  .letterhead {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    border-bottom: 2px solid #14332e;
    padding-bottom: 12px;
    margin-bottom: 18px;
  }
  .brand { color: #14332e; font-size: 22px; font-weight: 800; }
  .tagline { color: #5f6d68; font-size: 12px; margin-top: 2px; }
  .meta { text-align: right; color: #5f6d68; font-size: 11px; }
  .reportTitle { color: #14332e; font-size: 18px; font-weight: 800; margin: 0 0 14px; }
  .summaryGrid { display: flex; gap: 10px; margin-bottom: 16px; }
  .summaryCard {
    flex: 1;
    background: #f7f5ef;
    border: 1px solid #e6dfd1;
    border-radius: 8px;
    padding: 10px 12px;
  }
  .summaryLabel { color: #5f6d68; font-size: 10px; text-transform: uppercase; font-weight: 800; letter-spacing: 0.04em; }
  .summaryValue { color: #14332e; font-size: 20px; font-weight: 900; margin-top: 4px; }
  .summaryValueSmall { font-size: 14px; }
  .summaryValue.negative { color: #793915; }
  .summaryValue.positive { color: #31594f; }
  .summaryText { color: #2f423d; font-size: 13px; line-height: 1.6; }
  .attentionBanner {
    background: #fff2d8;
    border: 1px solid #e5c47a;
    border-radius: 8px;
    color: #7a5614;
    font-weight: 700;
    padding: 10px 14px;
    margin: 10px 0 16px;
    font-size: 12px;
  }
  .sectionTitle { color: #14332e; font-size: 14px; font-weight: 800; margin: 20px 0 8px; }
  .findingsList { display: flex; flex-direction: column; gap: 8px; }
  .finding { border-radius: 8px; border: 1px solid #e6dfd1; padding: 10px 12px; }
  .finding-info { background: #eef4f8; }
  .finding-watch { background: #fff2d8; }
  .finding-dispute { background: #f7e2dc; }
  .findingTitle { font-weight: 800; color: #14332e; font-size: 12.5px; }
  .findingText { color: #455a54; font-size: 12px; margin-top: 2px; }
  .chargeTable { width: 100%; border-collapse: collapse; font-size: 12px; }
  .chargeTable th {
    text-align: left;
    color: #5f6d68;
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    border-bottom: 1px solid #e6dfd1;
    padding: 6px 8px;
  }
  .chargeTable td { border-bottom: 1px solid #eee8d9; padding: 8px; vertical-align: top; }
  .chargeTableMuted td { color: #5f6d68; }
  .amountCol { text-align: right; white-space: nowrap; }
  .chargeName { font-weight: 800; color: #14332e; }
  .chargeExplanation { color: #4c5e58; margin-top: 2px; }
  .chargeAction { color: #793915; font-weight: 700; margin-top: 4px; }
  .statusTag {
    display: inline-block;
    border-radius: 5px;
    font-size: 10px;
    font-weight: 800;
    padding: 3px 7px;
    text-transform: uppercase;
  }
  .status-new { background: #f7e2dc; color: #793915; }
  .status-changed { background: #fff2d8; color: #7a5614; }
  .status-questionable { background: #f1d7ee; color: #63345e; }
  .status-expected { background: #e8eee2; color: #31594f; }
  .historyRowCurrent td { background: #f7f5ef; font-weight: 700; }
  .currentTag {
    background: #dcead5;
    color: #31594f;
    border-radius: 5px;
    font-size: 9px;
    font-weight: 800;
    padding: 2px 5px;
    text-transform: uppercase;
  }
  .rightsText { color: #36524b; font-size: 12px; }
  .footer {
    margin-top: 28px;
    border-top: 1px solid #e6dfd1;
    padding-top: 10px;
    color: #8a958f;
    font-size: 10px;
    line-height: 1.5;
  }
`;
